.TH PTAC 1 "2024-12-19" "ptac 1.0" "User Commands"
.SH NAME
ptac \- the prepending cat solution - prepend content to files or standard output
.SH SYNOPSIS
.B ptac
[\fIOPTION\fR]... [\fICONTENT\fR] [\fIFILE\fR]...
.br
.B ptac
[\fIOPTION\fR]... \fB-f\fR \fIPREPEND_FILE\fR [\fIFILE\fR]...
.SH DESCRIPTION
\fBptac\fR is a cat-like tool that focuses on prepending content to files or standard output. It supports all standard cat options while adding the ability to prepend strings or file content to one or multiple files.
.PP
If no FILE is specified or FILE is \-, read from standard input.
.SH OPTIONS
.TP
\fB\-A\fR, \fB\-\-show\-all\fR
equivalent to \fB\-vET\fR
.TP
\fB\-b\fR, \fB\-\-number\-nonblank\fR
number nonempty output lines, overrides \fB\-n\fR
.TP
\fB\-e\fR
equivalent to \fB\-vE\fR
.TP
\fB\-E\fR, \fB\-\-show\-ends\fR
display $ at end of each line
.TP
\fB\-f\fR, \fB\-\-file\fR \fIFILE\fR
prepend content from FILE
.TP
\fB\-n\fR, \fB\-\-number\fR
number all output lines
.TP
\fB\-s\fR, \fB\-\-squeeze\-blank\fR
suppress repeated empty output lines
.TP
\fB\-t\fR
equivalent to \fB\-vT\fR
.TP
\fB\-T\fR, \fB\-\-show\-tabs\fR
display TAB characters as ^I
.TP
\fB\-u\fR
(ignored, for compatibility)
.TP
\fB\-v\fR, \fB\-\-show\-nonprinting\fR
use ^ and M- notation, except for LFD and TAB
.TP
\fB\-\-help\fR
display this help and exit
.TP
\fB\-\-version\fR
output version information and exit
.SH EXAMPLES
.TP
.B ptac "Header line" file.txt
Prepend string to file content
.TP
.B ptac \-f header.txt file.txt
Prepend file content
.TP
.B ptac \-n "Line " file.txt
Prepend with line numbers
.TP
.B echo "data" | ptac "Header:"
Prepend to stdin
.TP
.B ptac "Start:" file1.txt file2.txt
Prepend to multiple files
.TP
.B ptac \-E "Header$" file.txt
Prepend showing line endings
.TP
.B ptac \-s "Header" file.txt
Prepend and squeeze blank lines
.SH NOTES
When prepending to multiple files, each file gets the same prepended content.
.PP
The tool maintains compatibility with standard cat options while focusing on prepending functionality.
.SH SEE ALSO
.BR cat (1)
.SH BUGS
Report bugs to: http://github.com/stefan-hacks/ptac
.SH AUTHOR
Developed as a versatile prepending solution for Unix-like systems.
.SH COPYRIGHT
Copyright © 2024 MIT License.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
